name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - run: pnpm install
      - run: pnpm check:all

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - run: pnpm install
      - run: pnpm build

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright dependencies
        run: pnpm exec playwright install

      - name: Run E2E tests
        run: pnpm test
