name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - run: npm i
      - run: npm run check:all

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - run: npm i
      - run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test:unit

  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Install Playwright dependencies
        run: npx playwright install

      - name: Run E2E tests
        run: npm run test
